version: '3'

services:
  nest:
    container_name: nest
    build: 
      context: ./docker
    working_dir: /usr/src/app
    tty: true
    networks:
      - net
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    command: sh -c 'yarn install && yarn start:dev'

networks:
  net: